services:
  #
  # rabbitmq:
  #   image: rabbitmq:4-management
  #   hostname: rabbitmq
  #   ports:
  #     - "5672:5672"  # AMQP
  #     - "15672:15672" # Management UI
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #     - rabbitmq_log:/var/log/rabbitmq
  #
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: celery_db
      MYSQL_USER: celery_user
      MYSQL_PASSWORD: celery_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  # rabbitmq_data:
  # rabbitmq_log:
  mysql_data:
